import type { Apotheke, UserProfile, Termin } from "./types"

// Mock current user (Admin role for full access during development)
export const mockCurrentUser: UserProfile = {
  id: "user-1",
  full_name: "Sebastian Mayrhuber",
  email: "sebastian@mw-education.at",
  role: "admin",
  is_active: true,
  created_at: "2025-01-01T00:00:00Z",
}

export const mockTrainers: UserProfile[] = [
  mockCurrentUser,
  {
    id: "user-2",
    full_name: "Maria Huber",
    email: "maria@mw-education.at",
    role: "trainer",
    is_active: true,
    created_at: "2025-01-15T00:00:00Z",
  },
  {
    id: "user-3",
    full_name: "Thomas Berger",
    email: "thomas@mw-education.at",
    role: "trainer",
    is_active: true,
    created_at: "2025-02-01T00:00:00Z",
  },
]

export const mockApotheken: Apotheke[] = [
  {
    id: "apo-1",
    name: "Marien Apotheke",
    address: "Maria-Theresien-Str. 12",
    plz: "6020",
    ort: "Innsbruck",
    region: "Tirol",
    priority: "top_kunde",
    notes: "Ansprechpartner: Fr. Meier, bevorzugt Vormittagstermine",
    deleted_at: null,
    created_at: "2025-01-10T00:00:00Z",
    created_by: "user-1",
    termin_count: 8,
  },
  {
    id: "apo-2",
    name: "Stadt-Apotheke",
    address: "Hauptplatz 5",
    plz: "4020",
    ort: "Linz",
    region: "OÖ",
    priority: "normal",
    notes: "",
    deleted_at: null,
    created_at: "2025-01-12T00:00:00Z",
    created_by: "user-1",
    termin_count: 3,
  },
  {
    id: "apo-3",
    name: "Löwen Apotheke",
    address: "Bahnhofstr. 22",
    plz: "5020",
    ort: "Salzburg",
    region: "Salzburg",
    priority: "top_kunde",
    notes: "Großes Team, immer hohe TN-Zahlen",
    deleted_at: null,
    created_at: "2025-01-15T00:00:00Z",
    created_by: "user-1",
    termin_count: 12,
  },
  {
    id: "apo-4",
    name: "Apotheke zum Goldenen Adler",
    address: "Rathausplatz 1",
    plz: "6900",
    ort: "Bregenz",
    region: "Vorarlberg",
    priority: "normal",
    notes: "",
    deleted_at: null,
    created_at: "2025-02-01T00:00:00Z",
    created_by: "user-1",
    termin_count: 2,
  },
  {
    id: "apo-5",
    name: "Dreifaltigkeits Apotheke",
    address: "Landstr. 88",
    plz: "4040",
    ort: "Linz",
    region: "OÖ",
    priority: "normal",
    notes: "Parkplatz vorhanden, Eingang hinten",
    deleted_at: null,
    created_at: "2025-02-05T00:00:00Z",
    created_by: "user-1",
    termin_count: 5,
  },
  {
    id: "apo-6",
    name: "Salvator Apotheke",
    address: "Museumstr. 3",
    plz: "6020",
    ort: "Innsbruck",
    region: "Tirol",
    priority: "normal",
    notes: "",
    deleted_at: null,
    created_at: "2025-02-10T00:00:00Z",
    created_by: "user-1",
    termin_count: 4,
  },
  {
    id: "apo-7",
    name: "Engel Apotheke",
    address: "Getreidegasse 15",
    plz: "5020",
    ort: "Salzburg",
    region: "Salzburg",
    priority: "top_kunde",
    notes: "Premium-Kunde, direkte Leitung zum Filialleiter",
    deleted_at: null,
    created_at: "2025-02-12T00:00:00Z",
    created_by: "user-1",
    termin_count: 9,
  },
  {
    id: "apo-8",
    name: "Sonnen Apotheke",
    address: "Dornbirner Str. 44",
    plz: "6850",
    ort: "Dornbirn",
    region: "Vorarlberg",
    priority: "normal",
    notes: "",
    deleted_at: null,
    created_at: "2025-03-01T00:00:00Z",
    created_by: "user-1",
    termin_count: 1,
  },
]

export const mockTermine: Termin[] = [
  {
    id: "termin-1",
    tour_id: null,
    apotheke_id: "apo-1",
    trainer_id: "user-2",
    datum: "2026-02-18",
    zeit_start: "09:00",
    zeit_ende: "11:00",
    status: "fixiert",
    notiz: "",
    cancel_reason: null,
    created_by: "user-1",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "termin-2",
    tour_id: null,
    apotheke_id: "apo-3",
    trainer_id: "user-2",
    datum: "2026-02-19",
    zeit_start: "10:00",
    zeit_ende: "12:00",
    status: "geplant",
    notiz: "Evtl. 10 Min. später",
    cancel_reason: null,
    created_by: "user-1",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "termin-3",
    tour_id: null,
    apotheke_id: "apo-2",
    trainer_id: "user-3",
    datum: "2026-02-10",
    zeit_start: "14:00",
    zeit_ende: "16:00",
    status: "durchgefuehrt",
    notiz: "",
    cancel_reason: null,
    created_by: "user-1",
    created_at: "2026-01-20T00:00:00Z",
  },
]
